### ISSUE TITLE
[Feature Request] A function to copy a move with its child-objects.

### ISSUE THREAD

**Issue by Crispy13** [Kiloutre/TekkenMovesetExtractor#24]
Hi. It would be good that MovestEditor has a function to copy a move with its child objects(cancel, extraproperty, hitcondition, reaction list. etc.).

While i was working on editing moves, i felt the need for a function like this. It may seem nice to have an option to select child objects which are copied with.

**Comment by Kiloutre** [comment]
Yes, this has been planned for a while. I need to allow the creation and deletion of anything first (requirements, extraprops, etc), and then i'll move on to copying moves from other movesets (i think that's what you're refererring to?). 

It's just a bit of a hard task because moves have references to cancel and reaction lists, which both have references to other moves! So when importing a single move with all its dependences, it WILL end up importing dozens of other moves with all their hit conditions and requirements. Like if you were to import the standing move of another character, it would theoretically end up importing the whole movelist, because every single move is accessible from standing.
