### ISSUE TITLE
T7 Devil Jin's beam problem

### ISSUE THREAD

**Issue by kse181** [Kiloutre/TekkenMovesetExtractor#8]
![Honeycam 2020-05-31 01-27-30](https://user-images.githubusercontent.com/66022423/83333847-9fc23b00-a2dd-11ea-81e9-fbd0585fead2.gif)
T7 -> T7 imported one

![Honeycam 2020-05-31 01-31-12](https://user-images.githubusercontent.com/66022423/83333879-d009d980-a2dd-11ea-84b7-701760ae1983.gif)
original T7 one

as you can see it's not same

**Comment by Kiloutre** [comment]
This is normal behavior for when the laser hits a robot (Alisa, Jack). It happens because i allow character-specific interactions to happen with everyone, because character IDs have changed since tag2 and character-specific stuff would completely break otherwise. I don't think it's much of a problem, and bothering to detect if the opponent is a robot could be quite annoying
